### ISSUE TITLE
Error: unexpected server response (403)

### ISSUE THREAD

**Issue by willsheppard** [sidorares/crconsole#39]
Am I doing something wrong?

```
$ ./node_modules/.bin/crconsole
chrome://newtab/
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (403)
    at ClientRequest.<anonymous> (/home/ubuntu/dev/mega-scrobble/node_modules/ws/lib/WebSocket.js:585:19)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at Socket.socketOnData (_http_client.js:474:22)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:297:12)
Emitted 'error' event on Chrome instance at:
    at EventEmitter.<anonymous> (/home/ubuntu/dev/mega-scrobble/node_modules/chrome-remote-interface/index.js:55:47)
    at EventEmitter.emit (events.js:314:20)
    at EventEmitter.emit (domain.js:483:12)
    at WebSocket.<anonymous> (/home/ubuntu/dev/mega-scrobble/node_modules/chrome-remote-interface/lib/chrome.js:157:23)
    at WebSocket.emit (events.js:314:20)
    at WebSocket.EventEmitter.emit (domain.js:483:12)
    at ClientRequest.<anonymous> (/home/ubuntu/dev/mega-scrobble/node_modules/ws/lib/WebSocket.js:587:12)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)

$ ./node_modules/.bin/crconsole -V
1.4.0

$ chromium-browser --version
Chromium 123.0.6312.122 snap

$ cat /etc/*release | head -2
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
```

**Comment by james1236** [comment]
Solved this by using `--remote-allow-origins="*"` when starting google-chrome as recommended in #38
